import 'package:aprender_a_controlar/models/pregunta.dart';

const List<Pregunta> bancoPreguntas = [
  // 1. PE-GM-001 (Operación Invierno 2026 V4)
  Pregunta(
    enunciado: "¿En qué período rige oficialmente la Operación Invierno en Minera Los Pelambres?",
    opciones: ["Del 15 de abril al 15 de septiembre", "Del 1 de mayo al 31 de agosto", "Del 1 de abril al 30 de octubre"],
    correcta: 0,
    retroalimentacion: "La Operación Invierno rige desde el 15 de abril hasta el 15 de septiembre de cada año.",
    codigoProcedimiento: "PE-GM-001",
  ),
  Pregunta(
    enunciado: "¿Quién asume la dirección del Comité de Operación Invierno Mina ante la ausencia del Gerente Mina?",
    opciones: ["El Superintendente de Carguío y Transporte", "El Ingeniero Senior de Operaciones Mina", "El Jefe de Sala GIO"],
    correcta: 1,
    retroalimentacion: "En ausencia del Gerente Mina, sus funciones y liderazgo del comité son asumidos por el Senior de Operaciones Mina.",
    codigoProcedimiento: "PE-GM-001",
  ),
  Pregunta(
    enunciado: "¿Qué EPP específico es obligatorio portar para el ingreso a la mina en periodo invernal?",
    opciones: ["Ropa térmica y casco estándar", "Ropa de abrigo invernal, crampones y dos dispositivos DVA", "Lentes oscuros y zapatos estándar"],
    correcta: 1,
    retroalimentacion: "Es obligatorio portar ropa de abrigo invernal, crampones y dos unidades de detector de víctimas de avalanchas (DVA).",
    codigoProcedimiento: "PE-GM-001",
  ),
  Pregunta(
    enunciado: "¿Con cuántas horas de anticipación deben iniciarse las verificaciones previas a un evento climático?",
    opciones: ["12 horas", "24 horas", "48 horas"],
    correcta: 2,
    retroalimentacion: "Las verificaciones previas al evento deben comenzar obligatoriamente 48 horas antes de su inicio proyectado.",
    codigoProcedimiento: "PE-GM-001",
  ),
  Pregunta(
    enunciado: "¿A partir de qué alerta de invierno se prohíbe la circulación de buses con tracción 4x4?",
    opciones: ["Alerta Temprana", "Alerta 1", "Alerta 2 o superior"],
    correcta: 2,
    retroalimentacion: "Al decretarse la Alerta 2, no pueden circular buses de tracción 4x4. La evacuación de estos buses debe planificarse en Alerta 1.",
    codigoProcedimiento: "PE-GM-001",
  ),
  Pregunta(
    enunciado: "¿Cuál es la velocidad máxima permitida en las caravanas de subida y bajada de personal durante una alerta?",
    opciones: ["20 km/h", "30 km/h", "40 km/h"],
    correcta: 0,
    retroalimentacion: "El vehículo líder de la caravana debe mantener una velocidad máxima estricta de 20 km/h.",
    codigoProcedimiento: "PE-GM-001",
  ),
  Pregunta(
    enunciado: "¿Qué porcentaje de agua del estanque de los camiones aljibe debe mantenerse en nave de mantención como reserva de emergencia?",
    opciones: ["Un cuarto de estanque", "La mitad del estanque", "El estanque completo"],
    correcta: 1,
    retroalimentacion: "Se debe asegurar mantener los camiones aljibe con la mitad del estanque en nave de mantención para emergencias climáticas.",
    codigoProcedimiento: "PE-GM-001",
  ),
  Pregunta(
    enunciado: "¿Cuál es el límite de visibilidad establecido para detener de forma inmediata la operación de camiones CAEX?",
    opciones: ["Visibilidad menor a 150 metros", "Visibilidad menor a 100 metros por viento blanco", "Visibilidad menor a 50 metros"],
    correcta: 1,
    retroalimentacion: "Si la visibilidad por viento blanco es menor a 100 metros, la operación de camiones CAEX se debe detener inmediatamente.",
    codigoProcedimiento: "PE-GM-001",
  ),
  Pregunta(
    enunciado: "¿Cuál es la prioridad número 1 establecida para el retiro de nieve y apertura de accesos post-evento climático?",
    opciones: ["Estacionamiento 3060", "El camino COM hacia el Hotel Mina", "Planta de Enaex"],
    correcta: 1,
    retroalimentacion: "La prioridad 1 de apertura de accesos es el camino principal que conecta el COM con el Hotel Mina.",
    codigoProcedimiento: "PE-GM-001",
  ),
  Pregunta(
    enunciado: "¿Cuáles son los principales riesgos invernales asociados a la alta montaña que busca mitigar este plan?",
    opciones: ["Deslizamientos, temperaturas de -15°C y tormentas de arena", "Bajas temperaturas, caminos congelados, viento blanco e interrupción de rutas por nieve", "Tormentas eléctricas únicamente"],
    correcta: 1,
    retroalimentacion: "El procedimiento busca mitigar los riesgos derivados de bajas temperaturas, hielo en rutas, viento blanco e interrupciones viales.",
    codigoProcedimiento: "PE-GM-001",
  ),
  Pregunta(
    enunciado: "¿En qué sector geográfico se encuentra ubicada la mina a cielo abierto Los Pelambres?",
    opciones: ["Cordillera de los Andes, Provincia de Choapa", "Cordillera de la Costa, Región de Coquimbo", "Valle del Elqui, Salamanca"],
    correcta: 0,
    retroalimentacion: "Se ubica en la Cordillera de los Andes, en la Comuna de Salamanca, Provincia de Choapa, a unos 3.200 msnm.",
    codigoProcedimiento: "PE-GM-001",
  ),
  Pregunta(
    enunciado: "¿Cuáles son los dos límites de batería principales definidos para la operación invierno?",
    opciones: ["Área Mina y Camino Principal Portones - Garita Mina", "Hotel Mina y Campamento Chacay", "Garita Los Vilos y Portones Mauro"],
    correcta: 0,
    retroalimentacion: "El reglamento divide las responsabilidades entre el Área Mina (desde Garita Mina al COM) y el Camino Principal (Portones - Garita Mina).",
    codigoProcedimiento: "PE-GM-001",
  ),
  Pregunta(
    enunciado: "¿Qué brigada de rescate está presente de forma continua en el rajo durante el invierno?",
    opciones: ["Brigada de Rescate las 24 horas del día, los 7 días de la semana", "Brigada externa de bomberos de Salamanca", "Paramédicos del policlínico solamente"],
    correcta: 0,
    retroalimentacion: "Se cuenta con una brigada de rescate permanente las 24 horas del día, los 7 días de la semana en el rajo.",
    codigoProcedimiento: "PE-GM-001",
  ),
  Pregunta(
    enunciado: "¿Cuál es el rol del Ingeniero Senior de Operaciones Mina respecto a las reuniones pre-evento climático?",
    opciones: ["Citar y liderar la Reunión de Coordinación de Evento Climático y levantar acta", "Autorizar el ingreso de buses 4x4", "Controlar la Isoterma Cero en los tranques"],
    correcta: 0,
    retroalimentacion: "El Senior de Operaciones Mina es responsable de coordinar transversalmente los preparativos, liderar la reunión y levantar acta.",
    codigoProcedimiento: "PE-GM-001",
  ),
  Pregunta(
    enunciado: "¿Qué nivel de alerta se decreta cuando el pronóstico indica precipitaciones acumuladas de 20 cm o más dentro de las próximas 12 horas?",
    opciones: ["Alerta Temprana", "Alerta 1", "Alerta 2"],
    correcta: 1,
    retroalimentacion: "Se activa la Alerta 1 ante un pronóstico de precipitación de 20 cm o más de nieve dentro de las siguientes 12 horas.",
    codigoProcedimiento: "PE-GM-001",
  ),

  // 2. PRO-OP-CSO-MLP-03 (Postura de Cadenas 2026)
  Pregunta(
    enunciado: "¿En qué neumáticos de un vehículo a motor se deben instalar las cadenas para nieve?",
    opciones: ["En las ruedas delanteras únicamente", "En las ruedas motrices", "En las cuatro ruedas obligatoriamente"],
    correcta: 1,
    retroalimentacion: "Las cadenas se instalan en las ruedas que proveen tracción (ruedas motrices) al vehículo.",
    codigoProcedimiento: "PRO-OP-CSO-MLP-03",
  ),
  Pregunta(
    enunciado: "¿Qué herramienta se utiliza para cerrar las medialunas de las cadenas de nieve en camionetas?",
    opciones: ["Alicate universal", "Ajustador de cadenas", "Llave de cruz"],
    correcta: 1,
    retroalimentacion: "El ajustador de cadenas es la herramienta específica diseñada para cerrar y asegurar las medialunas.",
    codigoProcedimiento: "PRO-OP-CSO-MLP-03",
  ),
  Pregunta(
    enunciado: "Al instalar los tensores elásticos (pulpos) en las cadenas de nieve, se deben colocar de arriba hacia abajo.",
    opciones: ["Verdadero", "Falso"],
    correcta: 0,
    retroalimentacion: "Verdadero. La instalación de tensores de arriba hacia abajo previene lesiones en el rostro si un extremo se soltara.",
    codigoProcedimiento: "PRO-OP-CSO-MLP-03",
  ),
  Pregunta(
    enunciado: "¿Cuántos tensores elásticos se deben instalar como mínimo por cada cadena instalada en un neumático?",
    opciones: ["Uno", "Dos", "Tres"],
    correcta: 1,
    retroalimentacion: "Se deben colocar al menos dos tensores por neumático para asegurar un apriete uniforme de la cadena.",
    codigoProcedimiento: "PRO-OP-CSO-MLP-03",
  ),
  Pregunta(
    enunciado: "¿Cuál es la primera etapa del procedimiento para la postura o retiro de cadenas?",
    opciones: ["Desmontar la rueda", "Estacionar en área plana autorizada, apagar motor, sacar llaves, usar freno de mano y cuñas", "Colocar los tensores en el neumático"],
    correcta: 1,
    retroalimentacion: "Toda labor comienza asegurando el vehículo en un sector plano, apagando el motor, retirando llaves e instalando cuñas y freno.",
    codigoProcedimiento: "PRO-OP-CSO-MLP-03",
  ),
  Pregunta(
    enunciado: "¿Qué elementos obligatorios debe contener la Caja de Operación Invierno de un vehículo liviano?",
    opciones: ["Pala, 3 cadenas, tensores, saco papero, estrobo, herramientas, linterna, frazada y cuñas", "Herramientas de mecánica general únicamente", "Un extintor adicional de 10 kg"],
    correcta: 0,
    retroalimentacion: "La caja de invierno debe equipar pala, cadenas, tensores, saco, estrobo de acero, destornilladores, alicate, linterna con pilas, frazada y cuñas.",
    codigoProcedimiento: "PRO-OP-CSO-MLP-03",
  ),
  Pregunta(
    enunciado: "¿Cuál es la cantidad máxima de pasajeros permitida en las camionetas que transitan en faena?",
    opciones: ["2 pasajeros", "3 pasajeros", "4 pasajeros"],
    correcta: 1,
    retroalimentacion: "El límite es de 3 pasajeros sentados (conductor, copiloto y dos trabajadores en el asiento de atrás), todos con cinturón.",
    codigoProcedimiento: "PRO-OP-CSO-MLP-03",
  ),
  Pregunta(
    enunciado: "¿Como debe alertar el conductor al personal en el exterior antes de mover el vehículo para acomodar las cadenas?",
    opciones: ["Haciendo sonar la radio", "Aplicando el código de bocinas", "Gritando por la ventana"],
    correcta: 1,
    retroalimentacion: "Se debe usar el código de bocina reglamentario antes de cualquier desplazamiento.",
    codigoProcedimiento: "PRO-OP-CSO-MLP-03",
  ),
  Pregunta(
    enunciado: "¿En qué condiciones de la carpeta de rodado es obligatorio transitar con cadenas en vehículos 4x4?",
    opciones: ["Carpeta negra", "Carpeta semi-blanca", "Carpeta blanca (totalmente cubierta de nieve)"],
    correcta: 2,
    retroalimentacion: "En carpeta blanca es obligatorio el uso de cadenas para nieve en todos los vehículos que transiten por el área mina.",
    codigoProcedimiento: "PRO-OP-CSO-MLP-03",
  ),
  Pregunta(
    enunciado: "¿Qué se debe hacer con las cadenas si presentan algún tipo de daño o eslabones rotos?",
    opciones: ["Repararlas con alambres en terreno", "Gestionar inmediatamente su reposición con el área de mantención", "Usarlas con precaución"],
    correcta: 1,
    retroalimentacion: "Las cadenas defectuosas o dañadas no deben ser utilizadas; deben reponerse por completo para evitar desprendimientos.",
    codigoProcedimiento: "PRO-OP-CSO-MLP-03",
  ),
  Pregunta(
    enunciado: "Al instalar cadenas en una retroexcavadora, ¿qué debe hacer el operador para facilitar la maniobra antes de subir la cadena?",
    opciones: ["Desmontar las llantas traseras", "Levantar los estabilizadores para elevar los neumáticos del suelo", "Desinflar los neumáticos"],
    correcta: 1,
    retroalimentacion: "El operador debe utilizar los estabilizadores para levantar los neumáticos y permitir una postura cómoda de la cadena.",
    codigoProcedimiento: "PRO-OP-CSO-MLP-03",
  ),
  Pregunta(
    enunciado: "¿Cuántas personas como mínimo se recomienda que participen en la postura de cadenas de equipo pesado (como la retroexcavadora)?",
    opciones: ["Una persona", "De 2 a 3 personas", "Cinco personas"],
    correcta: 1,
    retroalimentacion: "Se necesitan de 2 a 3 personas para subir y posicionar la cadena en neumáticos de equipo pesado de forma segura.",
    codigoProcedimiento: "PRO-OP-CSO-MLP-03",
  ),
  Pregunta(
    enunciado: "En las camionetas, ¿de qué forma se deben tensar los pulpos elásticos tras la colocación de la cadena?",
    opciones: ["Se deben enganchar uniformemente de arriba hacia abajo para evitar que cuelgue", "Se amarra al chasis de la camioneta", "Se deja colgando libremente"],
    correcta: 0,
    retroalimentacion: "Los tensores se instalan de arriba hacia abajo para lograr el mayor apriete posible y evitar extremos sueltos.",
    codigoProcedimiento: "PRO-OP-CSO-MLP-03",
  ),
  Pregunta(
    enunciado: "Si un conductor transita sin cadenas en un tramo considerado obligatorio por la Operación Invierno, ¿en qué sistema informático se reportará esta infracción?",
    opciones: ["Sistema SAP EHS", "Sistema Gauss Control", "Software Teletrac Navman"],
    correcta: 0,
    retroalimentacion: "Circular sin cadenas en tramos obligatorios se reporta directamente en el sistema SAP EHS.",
    codigoProcedimiento: "PRO-OP-CSO-MLP-03",
  ),
  Pregunta(
    enunciado: "¿En cuál de los siguientes puntos del camino está habilitado y señalizado el retiro e instalación de cadenas para el tramo Portones - Chacay - Mina?",
    opciones: ["Km 24.4 Hotel Mina", "Cualquier curva con espacio", "En la garita de Salamanca"],
    correcta: 0,
    retroalimentacion: "El Km 24.4 Hotel Mina es uno de los sectores oficiales autorizados y señalizados para la postura y retiro de cadenas.",
    codigoProcedimiento: "PRO-OP-CSO-MLP-03",
  ),

  // 3. PRO-OP-MLP-08 (Traslado y Uso de Caseta)
  Pregunta(
    enunciado: "¿Cuál es la velocidad máxima permitida al trasladar una caseta por el camino industrial y sector mina?",
    opciones: ["30 km/h", "40 km/h", "55 km/h"],
    correcta: 1,
    retroalimentacion: "Al trasladar carros de arrastre o casetas la velocidad máxima de conducción es de 40 km/h.",
    codigoProcedimiento: "PRO-OP-MLP-08",
  ),
  Pregunta(
    enunciado: "Al trasladar casetas o carros mato frente a curvas, rotondas o pendientes pronunciadas, ¿cuál es la velocidad máxima permitida?",
    opciones: ["10 km/h", "20 km/h", "30 km/h"],
    correcta: 0,
    retroalimentacion: "La velocidad debe reducirse a un máximo de 10 km/h en curvas, rotondas y peraltes con remolques.",
    codigoProcedimiento: "PRO-OP-MLP-08",
  ),
  Pregunta(
    enunciado: "¿Qué acción de seguridad se debe realizar con el extintor de la caseta antes de iniciar el traslado?",
    opciones: ["Dejarlo en su soporte de interior", "Retirarlo y llevarlo protegido en la cabina de la camioneta", "Descargarlo parcialmente"],
    correcta: 1,
    retroalimentacion: "Se debe retirar de la caseta y trasladar en la camioneta para evitar que quede expuesto a la intemperie y se dañe.",
    codigoProcedimiento: "PRO-OP-MLP-08",
  ),
  Pregunta(
    enunciado: "¿Para qué uso exclusivo está destinada la energía solar de los paneles en las casetas de control?",
    opciones: ["Para usar el microondas", "Únicamente para luces interiores y exteriores (12V)", "Para recargar baterías de vehículos"],
    correcta: 1,
    retroalimentacion: "El sistema fotovoltaico solar solo provee energía de 12V para la iluminación de la caseta.",
    codigoProcedimiento: "PRO-OP-MLP-08",
  ),
  Pregunta(
    enunciado: "¿Está permitido utilizar el microondas y el hervidor de forma simultánea con el generador eléctrico de la caseta?",
    opciones: ["Sí, el generador tiene capacidad", "No, se deben usar estrictamente por separado", "Sí, pero solo en el turno de día"],
    correcta: 1,
    retroalimentacion: "Está prohibido usar ambos electrodomésticos simultáneamente para no sobrecargar el generador de la caseta.",
    codigoProcedimiento: "PRO-OP-MLP-08",
  ),
  Pregunta(
    enunciado: "¿A qué distancia mínima con respecto al pretil debe quedar estacionada y estabilizada la caseta?",
    opciones: ["1.0 metro", "1.5 metros", "2.0 metros"],
    correcta: 1,
    retroalimentacion: "La caseta debe quedar instalada y nivelada a una distancia mínima de seguridad de 1.5 metros con respecto al pretil.",
    codigoProcedimiento: "PRO-OP-MLP-08",
  ),
  Pregunta(
    enunciado: "Al desenganchar la caseta de la camioneta, ¿cuál debe ser el estado del neumático de la caseta?",
    opciones: ["Debe quedar suspendido o libre de carga (sin peso)", "Debe estar con el freno de mano activado pero con peso", "Debe estar sobre cuñas de madera"],
    correcta: 0,
    retroalimentacion: "El remolque debe bajarse a una altura segura y las patas estabilizadoras deben sostener el peso de la caseta, liberando los neumáticos.",
    codigoProcedimiento: "PRO-OP-MLP-08",
  ),
  Pregunta(
    enunciado: "¿A qué distancia debe ubicarse el personal de apoyo que ayuda al conductor a retroceder para el enganche de la caseta?",
    opciones: ["A 1 metro y al centro", "A un mínimo de 2 metros y siempre visible para el conductor", "A 5 metros detrás de la caseta"],
    correcta: 1,
    retroalimentacion: "Debe situarse a 2 metros al costado del enganche, nunca en línea de fuego ni en puntos ciegos.",
    codigoProcedimiento: "PRO-OP-MLP-08",
  ),
  Pregunta(
    enunciado: "¿Qué instrumento se debe utilizar para verificar que la caseta quede perfectamente horizontal al instalarla?",
    opciones: ["Un nivel de burbuja", "Un flexómetro", "A ojo del supervisor"],
    correcta: 0,
    retroalimentacion: "Es obligatorio usar un nivel de burbuja para asegurar que los estabilizadores de la caseta mantengan el plano horizontal.",
    codigoProcedimiento: "PRO-OP-MLP-08",
  ),
  Pregunta(
    enunciado: "¿Cuál es la velocidad máxima permitida al realizar maniobras de retroceso para acoplar la caseta?",
    opciones: ["5 km/h", "10 km/h", "15 km/h"],
    correcta: 0,
    retroalimentacion: "Las maniobras de aproximación marcha atrás para el enganche de la caseta deben realizarse a no más de 5 km/h.",
    codigoProcedimiento: "PRO-OP-MLP-08",
  ),
  Pregunta(
    enunciado: "¿Qué plataforma satelital o sistema de monitoreo GPS utiliza la línea de mando para fiscalizar los límites de velocidad del traslado de casetas?",
    opciones: ["Teletrac Navman Director", "Gauss Control", "SAP EHS"],
    correcta: 0,
    retroalimentacion: "Se fiscaliza mediante la plataforma Teletrac Navman Director para verificar que no excedan las velocidades permitidas.",
    codigoProcedimiento: "PRO-OP-MLP-08",
  ),
  Pregunta(
    enunciado: "¿Por qué es crítico verificar la limpieza de los conectores eléctricos entre la camioneta y la caseta antes de un traslado?",
    opciones: ["Para evitar cortocircuitos en el alternador", "Para asegurar el correcto funcionamiento de las luces de tránsito (freno, direccionales, etc.)", "Para no descargar los paneles solares"],
    correcta: 1,
    retroalimentacion: "Los conectores sucios o con barro impiden el contacto eléctrico y provocan fallas en las luces reglamentarias de tránsito del remolque.",
    codigoProcedimiento: "PRO-OP-MLP-08",
  ),
  Pregunta(
    enunciado: "¿Cuál es el tiempo aproximado de autonomía eléctrica que proveen las baterías de los paneles solares de la caseta?",
    opciones: ["De 1 a 2 horas", "De 3 a 4 horas", "Toda la noche"],
    correcta: 1,
    retroalimentacion: "Las baterías de los paneles solares otorgan aproximadamente de 3 a 4 horas de energía autónoma a la caseta.",
    codigoProcedimiento: "PRO-OP-MLP-08",
  ),
  Pregunta(
    enunciado: "En caso de fallas en las luces del remolque que no se solucionen con limpieza, ¿cuál es el procedimiento a seguir?",
    opciones: ["Trasladar la caseta de día con luces intermitentes de la camioneta", "Programar la bajada a taller certificado a través de una solicitud de Permiso Especial (PEC)", "Reparar el cableado en terreno con cinta aisladora"],
    correcta: 1,
    retroalimentacion: "Si las luces fallan, se debe solicitar el PEC para bajar el remolque a un taller autorizado.",
    codigoProcedimiento: "PRO-OP-MLP-08",
  ),
  Pregunta(
    enunciado: "¿Qué sistema de calefacción de respaldo tiene el sistema de supresión de polvo de la caseta en caso de congelamiento de cañerías del sistema nuevo?",
    opciones: ["Calentadores portátiles a gas", "Un sistema de respaldo sin cañerías calefaccionadas que debe mantenerse vacío", "Riego manual con agua caliente"],
    correcta: 1,
    retroalimentacion: "Se dispone de un sistema de respaldo sin cañerías calefaccionadas que debe vaciarse para evitar su congelación cuando no se use.",
    codigoProcedimiento: "PRO-OP-MLP-08",
  ),

  // 4. PRO-OP-MLP-CS-02 (Conducción de Vehículo Liviano)
  Pregunta(
    enunciado: "¿Cuál es la velocidad máxima permitida en áreas de campamento, oficinas y talleres?",
    opciones: ["20 km/h", "30 km/h", "40 km/h"],
    correcta: 1,
    retroalimentacion: "En campamentos, oficinas, comedores y áreas de personal la velocidad límite es de 30 km/h.",
    codigoProcedimiento: "PRO-OP-MLP-CS-02",
  ),
  Pregunta(
    enunciado: "¿Cuál es la velocidad máxima permitida en caminos industriales y operativos generales de la mina?",
    opciones: ["50 km/h", "60 km/h", "70 km/h"],
    correcta: 0,
    retroalimentacion: "La velocidad máxima de conducción general en rutas industriales internas de faena es de 50 km/h.",
    codigoProcedimiento: "PRO-OP-MLP-CS-02",
  ),
  Pregunta(
    enunciado: "¿Qué sanción se aplica a un conductor que circule a 70 km/h o más al interior de las instalaciones de la minera?",
    opciones: ["Amonestación verbal", "Suspensión de licencia por 30 días", "Caducidad indefinida de la Autorización Interna de Conducir (AIC)"],
    correcta: 2,
    retroalimentacion: "Conducir a 70 km/h o más es una falta gravísima que implica la pérdida definitiva de la licencia interna de conducción.",
    codigoProcedimiento: "PRO-OP-MLP-CS-02",
  ),
  Pregunta(
    enunciado: "¿Qué dispositivo tecnológico de Gauss Control evalúa las capacidades cognitivas antes del inicio de la jornada?",
    opciones: ["Tótem de oximetría", "Dispositivo COGNUS", "Sistema CAS"],
    correcta: 1,
    retroalimentacion: "El dispositivo COGNUS realiza la medición diaria del estado de fatiga y aptitud cognitiva de los conductores.",
    codigoProcedimiento: "PRO-OP-MLP-CS-02",
  ),
  Pregunta(
    enunciado: "Al cambiar una rueda pinchada, ¿dónde se debe colocar la rueda como medida de seguridad en caso de falla de la gata?",
    opciones: ["En el pick-up de la camioneta", "Debajo de la carrocería de la camioneta", "A un costado del camino señalizada"],
    correcta: 1,
    retroalimentacion: "Ubicar la rueda removida bajo el chasis actúa como un soporte redundante si el sistema de la gata falla.",
    codigoProcedimiento: "PRO-OP-MLP-CS-02",
  ),
  Pregunta(
    enunciado: "¿Qué indican y para qué sirven los capuchones indicadores de torque instalados en las tuercas de las ruedas?",
    opciones: ["Para embellecer los neumáticos", "Permiten verificar visualmente si las tuercas se han aflojado", "Para regular la presión de aire"],
    correcta: 1,
    retroalimentacion: "Permiten una rápida inspección visual al inicio de turno; si las puntas de los capuchones pierden su alineación, la tuerca se ha soltado.",
    codigoProcedimiento: "PRO-OP-MLP-CS-02",
  ),
  Pregunta(
    enunciado: "¿Cuántas cuñas de seguridad son obligatorias para el estacionamiento de vehículos livianos?",
    opciones: ["Una cuña", "Dos cuñas", "Cuatro cuñas"],
    correcta: 1,
    retroalimentacion: "Es obligatorio instalar al menos 2 cuñas de seguridad acordes al diámetro de los neumáticos al estacionar.",
    codigoProcedimiento: "PRO-OP-MLP-CS-02",
  ),
  Pregunta(
    enunciado: "¿Con qué frecuencia se debe realizar la prueba de frenos, dirección y neumáticos al usar un vehículo?",
    opciones: ["Semanalmente", "En la primera hora de uso del turno y cada vez que se comparta el vehículo", "Solo ante fallas evidentes"],
    correcta: 1,
    retroalimentacion: "Debe probarse en la primera hora del turno y en cada relevo de conductor si el vehículo es compartido.",
    codigoProcedimiento: "PRO-OP-MLP-CS-02",
  ),
  Pregunta(
    enunciado: "¿Cuál es el código de bocina obligatorio para poner en marcha el motor de un vehículo?",
    opciones: ["Un bocinazo", "Dos bocinazos", "Tres bocinazos"],
    correcta: 0,
    retroalimentacion: "Un bocinazo indica puesta en marcha, dos indican avance y tres indican retroceso del vehículo.",
    codigoProcedimiento: "PRO-OP-MLP-CS-02",
  ),
  Pregunta(
    enunciado: "¿Está permitido hablar por celular utilizando un dispositivo de manos libres (bluetooth) mientras se conduce?",
    opciones: ["Sí, con volumen moderado", "No, está estrictamente prohibido usar el celular de cualquier forma durante la conducción", "Solo en caminos públicos"],
    correcta: 1,
    retroalimentacion: "La manipulación y el uso de celulares (incluso con manos libres) están prohibidos. Si se requiere hablar, se debe detener el vehículo en zona segura.",
    codigoProcedimiento: "PRO-OP-MLP-CS-02",
  ),
  Pregunta(
    enunciado: "Para obtener la licencia interna de conducción de Minera Los Pelambres, ¿cuál es la antigüedad mínima exigida con licencia municipal clase B?",
    opciones: ["1 año", "2 años", "3 años"],
    correcta: 2,
    retroalimentacion: "El conductor debe registrar al menos 3 años de antigüedad con posesión de su licencia municipal clase B.",
    codigoProcedimiento: "PRO-OP-MLP-CS-02",
  ),
  Pregunta(
    enunciado: "Qué evaluación conductual o de ruta se debe aprobar para solicitar por primera vez la Autorización Interna de Conducir (AIC)?",
    opciones: ["Prueba teórica municipal", "Prueba de ruta virtual utilizando un simulador de conducción", "Test psicológico escrito"],
    correcta: 1,
    retroalimentacion: "Se exige una prueba de ruta virtual en simulador de conducción para los solicitantes de primera vez de la AIC.",
    codigoProcedimiento: "PRO-OP-MLP-CS-02",
  ),
  Pregunta(
    enunciado: "En caso de cometer infracciones viales graves en la mina, ¿dónde se definen las sanciones aplicables al conductor?",
    opciones: ["En las políticas de la empresa contratista", "En la Tabla de Sanciones de los Reglamentos de Tránsito MLP y Tránsito Mina", "A criterio del supervisor de turno"],
    correcta: 1,
    retroalimentacion: "Las sanciones por infracciones se rigen estrictamente por la Tabla de Sanciones del Reglamento de Tránsito MLP y Tránsito Mina.",
    codigoProcedimiento: "PRO-OP-MLP-CS-02",
  ),
  Pregunta(
    enunciado: "¿Cuál es el código de bocina reglamentario para realizar la maniobra de retroceso con el vehículo?",
    opciones: ["Un bocinazo", "Dos bocinazos", "Tres bocinazos"],
    correcta: 2,
    retroalimentacion: "El código establece: 1 bocinazo para arrancar, 2 para avanzar y 3 para retroceder.",
    codigoProcedimiento: "PRO-OP-MLP-CS-02",
  ),
  Pregunta(
    enunciado: "¿Qué examen físico anual es obligatorio para los choferes que conducen en área mina o transportan personal?",
    opciones: ["Examen de orina simple", "Examen Psicosensotécnico riguroso anual", "Radiografía de tórax únicamente"],
    correcta: 1,
    retroalimentacion: "Los choferes de vehículos de carga, transporte de personal, escoltas y los que ingresan al rajo deben renovar anualmente el examen psicosensotécnico.",
    codigoProcedimiento: "PRO-OP-MLP-CS-02",
  ),

  // 5. PRO-OP-MLP-CS-07 (Control Operacional de Sondaje Diamantino)
  Pregunta(
    enunciado: "¿A qué distancia mínima con respecto a la máquina de perforación debe estar ubicado el mesón saca-testigos?",
    opciones: ["3 metros", "6 metros", "10 metros"],
    correcta: 1,
    retroalimentacion: "El mesón de saca-testigos debe situarse al menos a 6 metros de distancia de la sonda para evitar la línea de fuego.",
    codigoProcedimiento: "PRO-OP-MLP-CS-07",
  ),
  Pregunta(
    enunciado: "¿Cuál es el peso máximo permitido para la manipulación manual de bandejas de sondaje por parte de hombres?",
    opciones: ["20 kg", "25 kg", "30 kg"],
    correcta: 1,
    retroalimentacion: "La ley establece un límite de carga física máxima de 25 kg para el personal masculino.",
    codigoProcedimiento: "PRO-OP-MLP-CS-07",
  ),
  Pregunta(
    enunciado: "¿Cuál es el límite máximo de peso permitido para mujeres al manipular bandejas de sondajes?",
    opciones: ["15 kg", "20 kg", "25 kg"],
    correcta: 1,
    retroalimentacion: "El límite legal para mujeres es de 20 kg. Para no excederlo, se exige dejar 10 cm libres a cada lado de la bandeja al colocar los testigos.",
    codigoProcedimiento: "PRO-OP-MLP-CS-07",
  ),
  Pregunta(
    enunciado: "¿Qué marca física se debe realizar en la bandeja para identificar una reducción de diámetro de perforación (ej. HQ a NQ)?",
    opciones: ["Pintar la bandeja de otro color", "Colocar un taco que indique el cambio de diámetro y escribir con plumón dónde comienza", "Hacer una marca con soldadura"],
    correcta: 1,
    retroalimentacion: "Se debe colocar un taco rotulado y marcar con plumón la bandeja en la transición exacta de la reducción.",
    codigoProcedimiento: "PRO-OP-MLP-CS-07",
  ),
  Pregunta(
    enunciado: "¿Cada cuántos metros de avance en profundidad se debe colocar un taco de regularizado en la bandeja?",
    opciones: ["Cada 1 metro", "Cada 2 metros", "Cada 3 metros"],
    correcta: 1,
    retroalimentacion: "La regularización del avance se debe marcar con un taco de madera y plumón rojo cada 2 metros de profundidad.",
    codigoProcedimiento: "PRO-OP-MLP-CS-07",
  ),
  Pregunta(
    enunciado: "¿En qué sentido y dirección se debe realizar el traspaso de la muestra de testigos a la bandeja?",
    opciones: ["De abajo hacia arriba y de derecha a izquierda", "De arriba hacia abajo y de izquierda a derecha", "Es indiferente"],
    correcta: 1,
    retroalimentacion: "La muestra en bandeja se ordena siempre de arriba hacia abajo (dentro de las canaletas) y de izquierda a derecha en sentido de avance.",
    codigoProcedimiento: "PRO-OP-MLP-CS-07",
  ),
  Pregunta(
    enunciado: "¿Cómo se debe marcar una fractura inducida en el testigo para no confundirla con una natural?",
    opciones: ["Una línea azul continua", "Con dos líneas diagonales (//) en plumón azul", "Pintándola con corrector blanco"],
    correcta: 1,
    retroalimentacion: "Las fracturas inducidas por la manipulación del controlador o perforista se marcan con dos barras diagonales azules (//).",
    codigoProcedimiento: "PRO-OP-MLP-CS-07",
  ),
  Pregunta(
    enunciado: "¿Qué separa o delimita cada corrida o tramo de perforación individual en la bandeja?",
    opciones: ["Un taco de regularizado", "Un taco de bloqueo", "Un taco falso"],
    correcta: 1,
    retroalimentacion: "Cada sacada de barra o corrida se separa e identifica mediante un taco de bloqueo rotulado.",
    codigoProcedimiento: "PRO-OP-MLP-CS-07",
  ),
  Pregunta(
    enunciado: "Si se trabaja con una corona de diámetro HQ3, ¿qué elemento se debe usar obligatoriamente en el tubo interior durante la perforación?",
    opciones: ["Un resorte de zapata especial", "Dos lainas", "Agua con bentonita adicional"],
    correcta: 1,
    retroalimentacion: "Al trabajar con el sistema HQ3, es requisito utilizar dos lainas en el tubo interior para recibir el testigo de forma íntegra.",
    codigoProcedimiento: "PRO-OP-MLP-CS-07",
  ),
  Pregunta(
    enunciado: "¿Cuál es la altura máxima permitida para el acopio o apilamiento de bandejas de sondaje?",
    opciones: ["5 pisos", "10 pisos (equivalente a 40 bandejas)", "15 pisos"],
    correcta: 1,
    retroalimentacion: "Por estabilidad del almacenamiento, las bandejas se pueden apilar a un máximo de 10 pisos (40 bandejas en total).",
    codigoProcedimiento: "PRO-OP-MLP-CS-07",
  ),
  Pregunta(
    enunciado: "Al realizar la saca de testigo en tramos fracturados o molidos, ¿qué fórmula se utiliza para calcular la regularización si no hay un punto de referencia claro?",
    opciones: ["Fórmula de compensación de muestra por tramo de fracturado o molido", "Fórmula de interpolación lineal simple", "No se calcula, se deja en blanco"],
    correcta: 0,
    retroalimentacion: "Se aplican fórmulas de compensación (fórmulas 1 y 2 en el reglamento) utilizando los metrajes de los tacos de bloqueo y la longitud recuperada.",
    codigoProcedimiento: "PRO-OP-MLP-CS-07",
  ),
  Pregunta(
    enunciado: "¿Qué color de plumón se utiliza para marcar el metraje y datos en el taco de regularizado de la bandeja?",
    opciones: ["Plumón azul", "Plumón rojo", "Plumón negro"],
    correcta: 1,
    retroalimentacion: "Los datos en los tacos de regularización y las marcas en el testigo se realizan con plumón rojo.",
    codigoProcedimiento: "PRO-OP-MLP-CS-07",
  ),
  Pregunta(
    enunciado: "¿Qué información debe rotular el controlador en la pestaña inferior de la bandeja porta testigo?",
    opciones: ["Nombre del controlador y fecha", "Número de pozo, metraje Desde, metraje Hasta y número de bandeja", "Nombre de la empresa perforista"],
    correcta: 1,
    retroalimentacion: "Se rotula con plumón negro: Número de pozo, Desde (metraje inicial), Hasta (metraje final) y Número de bandeja.",
    codigoProcedimiento: "PRO-OP-MLP-CS-07",
  ),
  Pregunta(
    enunciado: "¿Cuál es el principal riesgo para la salud en las plataformas de sondaje y qué examen médico se realiza al personal para controlarlo?",
    opciones: ["Riesgo de Hipoacusia - Audiometría anual", "Exposición a polvo con contenido de sílice - Radiografía de tórax (Rx tórax)", "Hipotermia - Control de temperatura"],
    correcta: 1,
    retroalimentacion: "La exposición a polvo con sílice tiene riesgo de Silicosis, por lo que se exige control con Rx de tórax.",
    codigoProcedimiento: "PRO-OP-MLP-CS-07",
  ),
  Pregunta(
    enunciado: "¿Cómo deben apilarse y protegerse las bandejas completas de sondaje diamantino antes de su despacho?",
    opciones: ["Se deben tapar y apilar sobre un pallet o dos bandejas vacías paralelas en la base", "Se apilan sin tapa una sobre otra", "Se guardan en cajas de madera cerradas"],
    correcta: 0,
    retroalimentacion: "Las bandejas deben taparse y apilarse usando pallets o bandejas vacías paralelas invertidas como base.",
    codigoProcedimiento: "PRO-OP-MLP-CS-07",
  ),

  // 6. RO-GR-OPI-001 (Reglamento de Operaciones en Condiciones Climáticas Adversas)
  Pregunta(
    enunciado: "¿A partir de qué altitud (cota) es obligatorio portar y usar dos dispositivos RECCO?",
    opciones: ["Sobre cota 1.500", "Sobre cota 2.000 (El Quillay)", "Sobre cota 3.000"],
    correcta: 1,
    retroalimentacion: "El uso de RECCO es obligatorio al circular o trabajar sobre la cota 2.000 (Garita El Quillay hacia arriba).",
    codigoProcedimiento: "RO-GR-OPI-001",
  ),
  Pregunta(
    enunciado: "¿Dónde se deben portar los dos reflectores RECCO obligatorios por cada trabajador?",
    opciones: ["En el casco y chaleco", "Uno en el cordón del zapato de seguridad y otro en un bolsillo cerrado de 1ra o 2da capa", "Ambos en la mochila de seguridad"],
    correcta: 1,
    retroalimentacion: "Se portan uno en el zapato y otro en una capa de vestir interna, asegurando que no se pierdan si se retira la parka exterior.",
    codigoProcedimiento: "RO-GR-OPI-001",
  ),
  Pregunta(
    enunciado: "¿Qué características físicas del vehículo liviano prohíben su ingreso a faena durante una alerta?",
    opciones: ["Vehículos sin barra antivuelco", "Vehículos de color blanco o gris plateado en más del 50% de la carrocería", "Vehículos que no sean diésel"],
    correcta: 1,
    retroalimentacion: "El blanco y gris pierden visibilidad en la nieve, dificultando rescates, por lo que se restringe su ingreso.",
    codigoProcedimiento: "RO-GR-OPI-001",
  ),
  Pregunta(
    enunciado: "Si el escape de un vehículo queda obstruido por nieve durante una avalancha, ¿qué riesgo fatal se presenta si se deja el motor encendido?",
    opciones: ["Daño en el motor", "Muerte por inhalación de monóxido de carbono", "Congelamiento del combustible"],
    correcta: 1,
    retroalimentacion: "El gas no puede evacuarse libremente y entra al interior del vehículo, causando la muerte por asfixia rápidamente.",
    codigoProcedimiento: "RO-GR-OPI-001",
  ),
  Pregunta(
    enunciado: "¿Qué color y cantidad de bandas reflectantes deben tener los coligües de señalización de caminos?",
    opciones: ["Rojos y amarillos, con dos bandas reflectantes blancas", "Naranjos, con una banda blanca", "Verdes, con bandas amarillas"],
    correcta: 0,
    retroalimentacion: "Los coligües de delimitación invernal de caminos son de color rojo y amarillo, equipados con dos bandas reflectantes blancas.",
    codigoProcedimiento: "RO-GR-OPI-001",
  ),
  Pregunta(
    enunciado: "¿Cuántos días de stock de alimentos debe asegurar la Gerencia de Personas y Organización en campamentos ante cierres de camino?",
    opciones: ["5 días", "10 días para la dotación máxima", "15 días"],
    correcta: 1,
    retroalimentacion: "Se debe asegurar el abastecimiento alimentario en refugios y campamentos por un mínimo de 10 días de encierro.",
    codigoProcedimiento: "RO-GR-OPI-001",
  ),
  Pregunta(
    enunciado: "¿Qué se define como 'Personal Refugiable' bajo este reglamento?",
    opciones: ["Cualquier trabajador en faena", "Personal con habitabilidad asegurada en el refugio COM durante emergencias viales", "Personal médico de turno"],
    correcta: 1,
    retroalimentacion: "Es el personal que tiene asignación de cama/habitabilidad en el refugio COM para asegurar la continuidad y no requerir tránsito en tormenta.",
    codigoProcedimiento: "RO-GR-OPI-001",
  ),
  Pregunta(
    enunciado: "Ante una Alerta 3, ¿qué acción debe realizar el Jefe de Turno Mina con la maquinaria pesada expuesta a avalanchas?",
    opciones: ["Dejarla funcionando con luces encendidas", "Protegerla mediante orientación de la máquina, desplazamiento o evacuación", "Bajarla inmediatamente al Hotel Mina"],
    correcta: 1,
    retroalimentacion: "El Jefe de Turno Mina debe proteger la maquinaria pesada expuesta a aludes orientándola, desplazándola o evacuándola de la zona de riesgo.",
    codigoProcedimiento: "RO-GR-OPI-001",
  ),
  Pregunta(
    enunciado: "¿Qué periodo excepcional de inventario de stock mínimo de alimentos y combustibles se exige en campamentos ante temporales de invierno?",
    opciones: ["Mínimo 5 días", "Mínimo 10 días de encierro considerando la dotación máxima", "Mínimo 15 días"],
    correcta: 1,
    retroalimentacion: "Se exige contar con stock de alimentos y combustibles para un mínimo de 10 días de encierro de la dotación máxima.",
    codigoProcedimiento: "RO-GR-OPI-001",
  ),
  Pregunta(
    enunciado: "¿Qué canal o frecuencia de radio APX de Motorola se debe seleccionar en vehículos fuera de la mina para operaciones de invierno?",
    opciones: ["Canal General TFT - canal 01 (Op. Invierno IPSC en zona General Chacay)", "Frecuencia exclusiva de emergencias médicas", "Frecuencia de camiones CAEX"],
    correcta: 0,
    retroalimentacion: "En áreas fuera de la mina, se debe usar la zona 'General Chacay' y seleccionar el canal 'Op. Invierno IPSC' (o canal 01 en radios analógicas).",
    codigoProcedimiento: "RO-GR-OPI-001",
  ),
  Pregunta(
    enunciado: "Si se detecta la presencia de rocas caídas en el camino industrial, ¿qué debe hacer el conductor?",
    opciones: ["Detener el vehículo y retirar la roca del camino", "No retirar la roca por ningún motivo y avisar inmediatamente a Operación Invierno por radio o teléfono", "Esquivar la roca y continuar sin reportar"],
    correcta: 1,
    retroalimentacion: "Está prohibido retirar rocas caídas del camino debido al riesgo de nuevos desprendimientos; se debe avisar por radio o al teléfono de emergencias.",
    codigoProcedimiento: "RO-GR-OPI-001",
  ),
  Pregunta(
    enunciado: "¿Cuál es la condición que define un 'Evento Significativo' bajo este reglamento?",
    opciones: ["Acumulación de 5 cm de nieve", "Precipitaciones > 20 mm de agua o cm de nieve en menos de 12 horas, o > 40 mm/cm en 48 horas", "Vientos de más de 40 km/h"],
    correcta: 1,
    retroalimentacion: "Esa métrica activa los comités de operación invierno para evaluar las medidas de control.",
    codigoProcedimiento: "RO-GR-OPI-001",
  ),
  Pregunta(
    enunciado: "¿Quién tiene la autoridad exclusiva para declarar estados de alerta meteorológica y evacuaciones?",
    opciones: ["El Gerente de Operaciones", "La Gerencia de Seguridad y Salud Ocupacional, a través del Jefe de Operación Invierno", "El Gerente de Mina"],
    correcta: 1,
    retroalimentacion: "El Jefe de Operación Invierno, respaldado por la gerencia de SSO, emite y coordina las alertas y órdenes de evacuación.",
    codigoProcedimiento: "RO-GR-OPI-001",
  ),
  Pregunta(
    enunciado: "¿Cuál es la visibilidad máxima permitida para transitar sin escolta especial en carpeta blanca?",
    opciones: ["Tránsito libre para 4x4", "El tránsito sin escolta removedora de nieve está prohibido para buses", "200 metros"],
    correcta: 1,
    retroalimentacion: "El traslado de buses de personal en carpeta blanca exige la escolta de un equipo removedor de nieve en la ruta.",
    codigoProcedimiento: "RO-GR-OPI-001",
  ),
  Pregunta(
    enunciado: "¿Qué nivel de riesgo de avalancha (Escala Europea) representa una inestabilidad generalizada del manto nivoso con probabilidad de aludes en pendientes poco propicias?",
    opciones: ["Nivel 3 (Notable)", "Nivel 4 (Fuerte)", "Nivel 5 (Muy Fuerte)"],
    correcta: 2,
    retroalimentacion: "El Nivel 5 de la escala europea de aludes representa una inestabilidad general y alto peligro natural.",
    codigoProcedimiento: "RO-GR-OPI-001",
  ),
];
